name: ESP-IDF Build Check

on:
  pull_request:
    branches: [ main ]

jobs:
  build_poc:
    name: Build Saber POC for ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [ "esp32c6" ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Build with ESP-IDF
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: 'v5.4.1'
          target: ${{ matrix.target }}
          path: "."

  post_build_job:
    name: ESP-IDF Final Build Status
    needs: build_poc
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Check Status
        run: |
          if [[ "${{ needs.build_poc.result }}" != "success" ]]; then
            echo "One or more builds failed."
            exit 1
          fi
          echo "All builds passed successfully."
